### ISSUE TITLE
[pre-commit] - short options works, long are not working

### ISSUE THREAD

**Issue by izikeros** [rubik/xenon#48]
The problem is that xenon with "long options" (`--max-absolute B, --max-modules B, --max-average A`) does not find issues with complexity when used as pre-commit hook. When used with "short options" ( `-bB, -mB, -aA`) - it finds the issues with too complex code.

Here is my xenon hook definition in `.pre-commit-config.yaml`:

```yml
    # monitor code complexity
    -   repo: https://github.com/rubik/xenon
        rev: v0.9.0
        hooks:
            -   id: xenon
                args: [ --max-absolute B, --max-modules B, --max-average A ]
               #  args: [ -bB, -mB, -aA ]
```
I was running it on macOS.
